##### Copyright 2019 The TensorFlow Authors.

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 정형 데이터 다루기

<table class="tfo-notebook-buttons" align="left">
  <td>     <a target="_blank" href="https://www.tensorflow.org/tutorials/structured_data/feature_columns">     <img src="https://www.tensorflow.org/images/tf_logo_32px.png">     TensorFlow.org에서 보기</a>   </td>
  <td><a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs-l10n/blob/master/site/ko/tutorials/structured_data/feature_columns.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png">Google Colab에서 실행</a></td>
  <td><a target="_blank" href="https://github.com/tensorflow/docs-l10n/blob/master/site/ko/tutorials/structured_data/feature_columns.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png">GitHub에서 소그 보기</a></td>
  <td><a href="https://storage.googleapis.com/tensorflow_docs/docs-l10n/site/ko/tutorials/structured_data/feature_columns.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png">노트북 다운로드</a></td>
</table>

> 경고: 이 튜토리얼에 설명된 `tf.feature_columns` 모듈은 새 코드에는 권장되지 않습니다. [Keras 전처리 레이어](https://www.tensorflow.org/tutorials/structured_data/preprocessing_layers)에서 이 기능을 다룹니다. 마이그레이션 지침은 [마이그레이션 특성 열](../../guide/migrate/migrating_feature_columns.ipynb) 가이드를 참조하세요. `tf.feature_columns` 모듈은 TF1 `Estimators`와 함께 사용하도록 설계되었습니다. 이는 우리의 [호환성 보장](https://tensorflow.org/guide/versions) 대상에 해당하지만 보안 취약점 외에는 수정 사항이 제공되지 않습니다.

이 튜토리얼은 정형 데이터(structured data)를 다루는 방법을 소개합니다(예를 들어 CSV에서 읽은 표 형식의 데이터). [케라스](https://www.tensorflow.org/guide/keras)를 사용하여 모델을 정의하고 <a>특성 열</a>(feature column)을 사용하여 CSV의 열을 모델 훈련에 필요한 특성으로 매핑하겠습니다. 이 튜토리얼은 다음 내용을 포함합니다:

- [판다스](https://pandas.pydata.org/)(Pandas)를 사용하여 CSV 파일을 읽기
- [tf.data](https://www.tensorflow.org/guide/datasets)를 사용하여 행을 섞고 배치로 나누는 입력 파이프라인(pipeline)을 만들기
- CSV의 열을 feature_column을 사용해 모델 훈련에 필요한 특성으로 매핑하기
- 케라스를 사용하여 모델 구축, 훈련, 평가하기

## 데이터셋

We will use a simplified version of the PetFinder [dataset](https://www.kaggle.com/c/petfinder-adoption-prediction). There are several thousand rows in the CSV. Each row describes a pet, and each column describes an attribute. We will use this information to predict the speed at which the pet will be adopted.

다음은 이 데이터셋에 대한 [설명](https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/heart-disease.names)입니다. 수치형과 범주형 열이 모두 있다는 점을 주목하세요.

열 | 기술 | 특성 유형 | 데이터 형식
--- | --- | --- | ---
유형 | 동물의 종류(개, 고양이) | 범주 형 | 문자열
나이 | 애완 동물의 나이 | 수치 | 정수
품종 1 | 애완 동물의 기본 품종 | 범주 형 | 문자열
색상 1 | 애완 동물의 색상 1 | 범주 형 | 문자열
색상 2 | 애완 동물의 색상 2 | 범주 형 | 문자열
MaturitySize | 성장한 크기 | 범주 형 | 문자열
FurLength | 모피 길이 | 범주 형 | 문자열
예방 접종 | 애완 동물이 예방 접종을 받았습니다 | 범주 형 | 문자열
불임 시술 | 애완 동물이 불임 시술을 받았습니다 | 범주 형 | 문자열
건강 | 건강 상태 | 범주 형 | 문자열
회비 | 입양비 | 수치 | 정수
기술 | 이 애완 동물에 대한 프로필 작성 | 문자 | 문자열
PhotoAmt | 이 애완 동물의 업로드된 총 사진 | 수치 | 정수
AdoptionSpeed | 입양 속도 | 분류 | 정수

## 텐서플로와 필요한 라이브러리 임포트하기

In [2]:
!pip install sklearn

  Using cached sklearn-0.0.post1-py3-none-any.whl


In [3]:
import numpy as np
import pandas as pd

import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

2022-12-14 23:19:00.364639: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-12-14 23:19:00.364744: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-12-14 23:19:00.364754: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.


## 판다스로 데이터프레임 만들기

[판다스](https://pandas.pydata.org/)는 정형 데이터를 읽고 조작하는데 유용한 유틸리티 함수를 많이 제공하는 파이썬 라이브러리입니다. 판다스를 이용해 URL로부터 데이터를 다운로드하여 읽은 다음 데이터프레임으로 변환하겠습니다.

In [4]:
import pathlib

dataset_url = 'http://storage.googleapis.com/download.tensorflow.org/data/petfinder-mini.zip'
csv_file = 'datasets/petfinder-mini/petfinder-mini.csv'

tf.keras.utils.get_file('petfinder_mini.zip', dataset_url,
                        extract=True, cache_dir='.')
dataframe = pd.read_csv(csv_file)

   8192/1668792 [..............................] - ETA: 0s

1668792/1668792 [==============================] - 0s 0us/step


In [5]:
dataframe.head()

Type  Age                Breed1  Gender Color1    Color2 MaturitySize  \
0  Cat    3                 Tabby    Male  Black     White        Small   
1  Cat    1  Domestic Medium Hair    Male  Black     Brown       Medium   
2  Dog    1           Mixed Breed    Male  Brown     White       Medium   
3  Dog    4           Mixed Breed  Female  Black     Brown       Medium   
4  Dog    1           Mixed Breed    Male  Black  No Color       Medium   

  FurLength Vaccinated Sterilized   Health  Fee  \
0     Short         No         No  Healthy  100   
1    Medium   Not Sure   Not Sure  Healthy    0   
2    Medium        Yes         No  Healthy    0   
3     Short        Yes         No  Healthy  150   
4     Short         No         No  Healthy    0   

                                         Description  PhotoAmt  AdoptionSpeed  
0  Nibble is a 3+ month old ball of cuteness. He ...         1              2  
1  I just found it alone yesterday near my apartm...         2              0  
2  Their pregnant mother was dumped by her irresp...         7              3  
3  Good guard dog, very alert, active, obedience ...         8              2  
4  This handsome yet cute boy is up for adoption....         3              2

## 목표 변수 만들기

원래 데이터세트의 작업은 애완 동물이 입양되는 속도를 예측하는 것입니다(예: 첫번째 주, 첫번째 달, 처음 3개월 등). 이 튜토리얼에서는 이해를 돕기 위해 단순화해보겠습니다. 여기에서는 데이터세트를 이진 분류 문제로 변환하고 애완 동물이 입양되었는지 여부를 단순하게 예측합니다.

레이블 열을 수정한 후, 0은 애완 동물이 입양되지 않았음을 나타내고 1은 입양되었음을 나타냅니다.

In [6]:
# In the original dataset "4" indicates the pet was not adopted.
dataframe['target'] = np.where(dataframe['AdoptionSpeed']==4, 0, 1)

# Drop un-used columns.
dataframe = dataframe.drop(columns=['AdoptionSpeed', 'Description'])

## 데이터프레임을 훈련 세트, 검증 세트, 테스트 세트로 나누기

하나의 CSV 파일에서 데이터셋을 다운로드했습니다. 이를 훈련 세트, 검증 세트, 테스트 세트로 나누겠습니다.

In [7]:
train, test = train_test_split(dataframe, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), 'train examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

7383 train examples
1846 validation examples
2308 test examples


## tf.data를 사용하여 입력 파이프라인 만들기

그다음 [tf.data](https://www.tensorflow.org/guide/datasets)를 사용하여 데이터프레임을 감싸겠습니다. 이렇게 하면 특성 열을 사용하여 판다스 데이터프레임의 열을 모델 훈련에 필요한 특성으로 매핑할 수 있습니다. 아주 큰 CSV 파일(메모리에 들어갈 수 없을 정도로 큰 파일)을 다룬다면 tf.data로 디스크 디렉토리에서 데이터를 읽을 수 있습니다. 이런 내용은 이 튜토리얼에 포함되어 있지 않습니다.

In [8]:
# A utility method to create a tf.data dataset from a Pandas Dataframe
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('target')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

In [9]:
batch_size = 5 # A small batch sized is used for demonstration purposes
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

## 입력 파이프라인 이해하기

앞서 만든 입력 파이프라인을 호출하여 반환되는 데이터 포맷을 확인해 보겠습니다. 간단하게 출력하기 위해 작은 배치 크기를 사용합니다.

In [10]:
for feature_batch, label_batch in train_ds.take(1):
  print('Every feature:', list(feature_batch.keys()))
  print('A batch of ages:', feature_batch['Age'])
  print('A batch of targets:', label_batch )

Every feature: ['Type', 'Age', 'Breed1', 'Gender', 'Color1', 'Color2', 'MaturitySize', 'FurLength', 'Vaccinated', 'Sterilized', 'Health', 'Fee', 'PhotoAmt']
A batch of ages: tf.Tensor([ 6  1  1 24  6], shape=(5,), dtype=int64)
A batch of targets: tf.Tensor([1 1 1 0 0], shape=(5,), dtype=int64)


이 데이터셋은 (데이터프레임의) 열 이름을 키로 갖는 딕셔너리를 반환합니다. 데이터프레임 열의 값이 매핑되어 있습니다.

## 여러 종류의 특성 열 알아 보기

텐서플로는 여러 종류의 특성 열을 제공합니다. 이 절에서 몇 가지 특성 열을 만들어서 데이터프레임의 열을 변환하는 방법을 알아 보겠습니다.

In [11]:
# We will use this batch to demonstrate several types of feature columns
example_batch = next(iter(train_ds))[0]

In [12]:
# A utility method to create a feature column
# and to transform a batch of data
def demo(feature_column):
  feature_layer = layers.DenseFeatures(feature_column)
  print(feature_layer(example_batch).numpy())

### 수치형 열

특성 열의 출력은 모델의 입력이 됩니다(앞서 정의한 함수를 사용하여 데이터프레임의 각 열이 어떻게 변환되는지 알아 볼 것입니다). [수치형 열](https://www.tensorflow.org/api_docs/python/tf/feature_column/numeric_column)은 가장 간단한 종류의 열입니다. 이 열은 실수 특성을 표현하는데 사용됩니다. 이 열을 사용하면 모델은 데이터프레임 열의 값을 변형시키지 않고 그대로 전달 받습니다.

In [13]:
photo_count = feature_column.numeric_column('PhotoAmt')
demo(photo_count)

[[5.]
 [1.]
 [5.]
 [3.]
 [3.]]


심장병 데이터셋 데이터프레임의 대부분 열은 수치형입니다.

### 버킷형 열

종종 모델에 수치 값을 바로 주입하기 원치 않을 때가 있습니다. 대신 수치 값의 구간을 나누어 이를 기반으로 범주형으로 변환합니다. 원본 데이터가 사람의 나이를 표현한다고 가정해 보죠. 나이를 수치형 열로 표현하는 대신 [버킷형 열](https://www.tensorflow.org/api_docs/python/tf/feature_column/bucketized_column)(bucketized column)을 사용하여 나이를 몇 개의 버킷(bucket)으로 분할할 수 있습니다. 다음에 원-핫 인코딩(one-hot encoding)된 값은 각 열이 매칭되는 나이 범위를 나타냅니다.

In [14]:
age = feature_column.numeric_column('Age')
age_buckets = feature_column.bucketized_column(age, boundaries=[1, 3, 5])
demo(age_buckets)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


### 범주형 열

이 데이터셋에서 thal 열은 문자열입니다(예를 들어 'fixed', 'normal', 'reversible'). 모델에 문자열을 바로 주입할 수 없습니다. 대신 문자열을 먼저 수치형으로 매핑해야 합니다. 범주형 열(categorical column)을 사용하여 문자열을 원-핫 벡터로 표현할 수 있습니다. 문자열 목록은 [categorical_column_with_vocabulary_list](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_list)를 사용하여 리스트로 전달하거나 [categorical_column_with_vocabulary_file](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file)을 사용하여 파일에서 읽을 수 있습니다.

In [15]:
animal_type = feature_column.categorical_column_with_vocabulary_list(
      'Type', ['Cat', 'Dog'])

animal_type_one_hot = feature_column.indicator_column(animal_type)
demo(animal_type_one_hot)

[[0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]


### 임베딩 열

가능한 문자열이 몇 개가 있는 것이 아니라 범주마다 수천 개 이상의 값이 있는 경우를 상상해 보겠습니다. 여러 가지 이유로 범주의 개수가 늘어남에 따라 원-핫 인코딩을 사용하여 신경망을 훈련시키는 것이 불가능해집니다. 임베딩 열(embedding column)을 사용하면 이런 제한을 극복할 수 있습니다. 고차원 원-핫 벡터로 데이터를 표현하는 대신 [임베딩 열](https://www.tensorflow.org/api_docs/python/tf/feature_column/embedding_column)을 사용하여 저차원으로 데이터를 표현합니다. 이 벡터는 0 또는 1이 아니라 각 원소에 어떤 숫자도 넣을 수 있는 밀집 벡터(dense vector)입니다. 임베딩의 크기(아래 예제에서는 8입니다)는 튜닝 대상 파라미터입니다.

핵심 포인트: 범주형 열에 가능한 값이 많을 때는 임베딩 열을 사용하는 것이 최선입니다. 여기에서는 예시를 목적으로 하나를 사용하지만 완전한 예제이므로 나중에 다른 데이터셋에 수정하여 적용할 수 있습니다.

In [16]:
# Notice the input to the embedding column is the categorical column
# we previously created
breed1 = feature_column.categorical_column_with_vocabulary_list(
      'Breed1', dataframe.Breed1.unique())
breed1_embedding = feature_column.embedding_column(breed1, dimension=8)
demo(breed1_embedding)

[[ 0.10462465 -0.08802601  0.49442118  0.50809896 -0.1307346  -0.45663163
   0.22619165  0.09262637]
 [ 0.10462465 -0.08802601  0.49442118  0.50809896 -0.1307346  -0.45663163
   0.22619165  0.09262637]
 [ 0.10462465 -0.08802601  0.49442118  0.50809896 -0.1307346  -0.45663163
   0.22619165  0.09262637]
 [ 0.18392055  0.4108529   0.2024461  -0.05835994  0.48673633 -0.10636031
   0.3101833   0.25405502]
 [ 0.47967386  0.2694226   0.38421303  0.62339777  0.2811113  -0.00219993
  -0.08739576 -0.58554184]]


### 해시 특성 열

가능한 값이 많은 범주형 열을 표현하는 또 다른 방법은 [categorical_column_with_hash_bucket](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_hash_bucket)을 사용하는 것입니다. 이 특성 열은 입력의 해시(hash) 값을 계산한 다음 `hash_bucket_size` 크기의 버킷 중 하나를 선택하여 문자열을 인코딩합니다. 이 열을 사용할 때는 어휘 목록을 제공할 필요가 없고 공간을 절약하기 위해 실제 범주의 개수보다 훨씬 작게 해시 버킷(bucket)의 크기를 정할 수 있습니다.

핵심 포인트: 이 기법의 큰 단점은 다른 문자열이 같은 버킷에 매핑될 수 있다는 것입니다. 그럼에도 실전에서는 일부 데이터셋에서 잘 작동합니다.

In [17]:
breed1_hashed = feature_column.categorical_column_with_hash_bucket(
      'Breed1', hash_bucket_size=10)
demo(feature_column.indicator_column(breed1_hashed))

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 교차 특성 열

여러 특성을 연결하여 하나의 특성으로 만드는 것을 [교차 특성](https://developers.google.com/machine-learning/glossary/#feature_cross)(feature cross)이라고 합니다. 모델이 특성의 조합에 대한 가중치를 학습할 수 있습니다. 이 예제에서는 age와 thal의 교차 특성을 만들어 보겠습니다. `crossed_column`은 모든 가능한 조합에 대한 해시 테이블을 만들지 않고 `hashed_column` 매개변수를 사용하여 해시 테이블의 크기를 선택합니다.

In [18]:
crossed_feature = feature_column.crossed_column([age_buckets, animal_type], hash_bucket_size=10)
demo(feature_column.indicator_column(crossed_feature))

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


## 사용할 열 선택하기

여러 가지 특성 열을 사용하는 방법을 보았으므로 이제 이를 사용하여 모델을 훈련하겠습니다. 이 튜토리얼의 목적은 특성 열을 사용하는 완전한 코드(예를 들면 작동 방식)를 제시하는 것이므로 임의로 몇 개의 열을 선택하여 모델을 훈련하겠습니다.

핵심 포인트: 제대로 된 모델을 만들어야 한다면 대용량의 데이터셋을 사용하고 어떤 특성을 포함하는 것이 가장 의미있는지, 또 어떻게 표현해야 할지 신중하게 생각하세요.

In [19]:
feature_columns = []

# numeric cols
for header in ['PhotoAmt', 'Fee', 'Age']:
  feature_columns.append(feature_column.numeric_column(header))

In [20]:
# bucketized cols
age = feature_column.numeric_column('Age')
age_buckets = feature_column.bucketized_column(age, boundaries=[1, 2, 3, 4, 5])
feature_columns.append(age_buckets)

In [21]:
# indicator_columns
indicator_column_names = ['Type', 'Color1', 'Color2', 'Gender', 'MaturitySize',
                          'FurLength', 'Vaccinated', 'Sterilized', 'Health']
for col_name in indicator_column_names:
  categorical_column = feature_column.categorical_column_with_vocabulary_list(
      col_name, dataframe[col_name].unique())
  indicator_column = feature_column.indicator_column(categorical_column)
  feature_columns.append(indicator_column)

In [22]:
# embedding columns
breed1 = feature_column.categorical_column_with_vocabulary_list(
      'Breed1', dataframe.Breed1.unique())
breed1_embedding = feature_column.embedding_column(breed1, dimension=8)
feature_columns.append(breed1_embedding)

In [23]:
# crossed columns
age_type_feature = feature_column.crossed_column([age_buckets, animal_type], hash_bucket_size=100)
feature_columns.append(feature_column.indicator_column(age_type_feature))

### 특성 층 만들기

특성 열을 정의하고 나면 [DenseFeatures](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/DenseFeatures) 층을 사용해 케라스 모델에 주입할 수 있습니다.

In [24]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

앞서 특성 열의 작동 예를 보이기 위해 작은 배치 크기를 사용했습니다. 여기에서는 조금 더 큰 배치 크기로 입력 파이프라인을 만듭니다.

In [25]:
batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

## 모델 생성, 컴파일, 훈련

In [26]:
model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(128, activation='relu'),
  layers.Dropout(.1),
  layers.Dense(1)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(train_ds,
          validation_data=val_ds,
          epochs=10)

Epoch 1/10


  1/231 [..............................] - ETA: 10:47 - loss: 1.0849 - accuracy: 0.1562

  2/231 [..............................] - ETA: 42s - loss: 1.2271 - accuracy: 0.2969  

  3/231 [..............................] - ETA: 41s - loss: 1.0039 - accuracy: 0.4792

  4/231 [..............................] - ETA: 40s - loss: 0.8775 - accuracy: 0.5547

  5/231 [..............................] - ETA: 40s - loss: 1.0712 - accuracy: 0.5625

  9/231 [>.............................] - ETA: 25s - loss: 1.2481 - accuracy: 0.6215

 14/231 [>.............................] - ETA: 18s - loss: 1.1798 - accuracy: 0.6406

 21/231 [=>............................] - ETA: 14s - loss: 1.0527 - accuracy: 0.6250

 28/231 [==>...........................] - ETA: 10s - loss: 1.0354 - accuracy: 0.6339

 33/231 [===>..........................] - ETA: 9s - loss: 1.0521 - accuracy: 0.6458 

 39/231 [====>.........................] - ETA: 9s - loss: 0.9886 - accuracy: 0.6619

 45/231 [====>.........................] - ETA: 8s - loss: 0.9308 - accuracy: 0.6708

 52/231 [=====>........................] - ETA: 7s - loss: 0.8887 - accuracy: 0.6713

 60/231 [======>.......................] - ETA: 6s - loss: 0.8695 - accuracy: 0.6667

 67/231 [=======>......................] - ETA: 5s - loss: 0.8723 - accuracy: 0.6698

 74/231 [========>.....................] - ETA: 4s - loss: 0.8695 - accuracy: 0.6672

 82/231 [=========>....................] - ETA: 4s - loss: 0.8535 - accuracy: 0.6604

 88/231 [==========>...................] - ETA: 4s - loss: 0.8631 - accuracy: 0.6644

 95/231 [===========>..................] - ETA: 3s - loss: 0.8426 - accuracy: 0.6691

103/231 [============>.................] - ETA: 3s - loss: 0.8181 - accuracy: 0.6723

111/231 [=============>................] - ETA: 2s - loss: 0.8125 - accuracy: 0.6729

119/231 [==============>...............] - ETA: 2s - loss: 0.7948 - accuracy: 0.6775

127/231 [===============>..............] - ETA: 2s - loss: 0.7839 - accuracy: 0.6750

135/231 [================>.............] - ETA: 2s - loss: 0.7756 - accuracy: 0.6757

143/231 [=================>............] - ETA: 1s - loss: 0.7691 - accuracy: 0.6774

150/231 [==================>...........] - ETA: 1s - loss: 0.7631 - accuracy: 0.6802

158/231 [===================>..........] - ETA: 1s - loss: 0.7523 - accuracy: 0.6824

165/231 [====================>.........] - ETA: 1s - loss: 0.7449 - accuracy: 0.6826

173/231 [=====================>........] - ETA: 1s - loss: 0.7431 - accuracy: 0.6826

181/231 [======================>.......] - ETA: 0s - loss: 0.7374 - accuracy: 0.6820

189/231 [=======================>......] - ETA: 0s - loss: 0.7319 - accuracy: 0.6802

196/231 [========================>.....] - ETA: 0s - loss: 0.7257 - accuracy: 0.6810

204/231 [=========================>....] - ETA: 0s - loss: 0.7239 - accuracy: 0.6815

212/231 [==========================>...] - ETA: 0s - loss: 0.7173 - accuracy: 0.6832

220/231 [===========================>..] - ETA: 0s - loss: 0.7116 - accuracy: 0.6847

228/231 [============================>.] - ETA: 0s - loss: 0.7042 - accuracy: 0.6853

231/231 [==============================] - 7s 19ms/step - loss: 0.7021 - accuracy: 0.6859 - val_loss: 0.5517 - val_accuracy: 0.7183


Epoch 2/10


  1/231 [..............................] - ETA: 12s - loss: 0.7731 - accuracy: 0.7188

  9/231 [>.............................] - ETA: 1s - loss: 0.5852 - accuracy: 0.7014 

 17/231 [=>............................] - ETA: 1s - loss: 0.6050 - accuracy: 0.6949

 25/231 [==>...........................] - ETA: 1s - loss: 0.6020 - accuracy: 0.6988

 33/231 [===>..........................] - ETA: 1s - loss: 0.6119 - accuracy: 0.7045

 41/231 [====>.........................] - ETA: 1s - loss: 0.6218 - accuracy: 0.6944

 49/231 [=====>........................] - ETA: 1s - loss: 0.6184 - accuracy: 0.7105

 57/231 [======>.......................] - ETA: 1s - loss: 0.6234 - accuracy: 0.7155

 65/231 [=======>......................] - ETA: 1s - loss: 0.6107 - accuracy: 0.7125

 73/231 [========>.....................] - ETA: 1s - loss: 0.6050 - accuracy: 0.7072

 81/231 [=========>....................] - ETA: 1s - loss: 0.6054 - accuracy: 0.7049

 89/231 [==========>...................] - ETA: 0s - loss: 0.6026 - accuracy: 0.6966

 97/231 [===========>..................] - ETA: 0s - loss: 0.5911 - accuracy: 0.7062

105/231 [============>.................] - ETA: 0s - loss: 0.6002 - accuracy: 0.7071

113/231 [=============>................] - ETA: 0s - loss: 0.5998 - accuracy: 0.7060

121/231 [==============>...............] - ETA: 0s - loss: 0.5963 - accuracy: 0.7082

129/231 [===============>..............] - ETA: 0s - loss: 0.5940 - accuracy: 0.7083

137/231 [================>.............] - ETA: 0s - loss: 0.5934 - accuracy: 0.7096

145/231 [=================>............] - ETA: 0s - loss: 0.5888 - accuracy: 0.7110

153/231 [==================>...........] - ETA: 0s - loss: 0.5870 - accuracy: 0.7100

161/231 [===================>..........] - ETA: 0s - loss: 0.5851 - accuracy: 0.7112

169/231 [====================>.........] - ETA: 0s - loss: 0.5815 - accuracy: 0.7136

177/231 [=====================>........] - ETA: 0s - loss: 0.5838 - accuracy: 0.7113

185/231 [=======================>......] - ETA: 0s - loss: 0.5835 - accuracy: 0.7095

193/231 [========================>.....] - ETA: 0s - loss: 0.5832 - accuracy: 0.7081

201/231 [=========================>....] - ETA: 0s - loss: 0.5818 - accuracy: 0.7099

209/231 [==========================>...] - ETA: 0s - loss: 0.5813 - accuracy: 0.7110

217/231 [===========================>..] - ETA: 0s - loss: 0.5785 - accuracy: 0.7108

225/231 [============================>.] - ETA: 0s - loss: 0.5758 - accuracy: 0.7114

231/231 [==============================] - 2s 8ms/step - loss: 0.5749 - accuracy: 0.7131 - val_loss: 0.5445 - val_accuracy: 0.7297


Epoch 3/10


  1/231 [..............................] - ETA: 14s - loss: 0.6863 - accuracy: 0.7188

  8/231 [>.............................] - ETA: 1s - loss: 0.5049 - accuracy: 0.7344 

 16/231 [=>............................] - ETA: 1s - loss: 0.4997 - accuracy: 0.7500

 24/231 [==>...........................] - ETA: 1s - loss: 0.5131 - accuracy: 0.7461

 32/231 [===>..........................] - ETA: 1s - loss: 0.5095 - accuracy: 0.7529

 39/231 [====>.........................] - ETA: 1s - loss: 0.5159 - accuracy: 0.7476

 47/231 [=====>........................] - ETA: 1s - loss: 0.5211 - accuracy: 0.7513

 55/231 [======>.......................] - ETA: 1s - loss: 0.5202 - accuracy: 0.7466

 63/231 [=======>......................] - ETA: 1s - loss: 0.5127 - accuracy: 0.7485

 71/231 [========>.....................] - ETA: 1s - loss: 0.5128 - accuracy: 0.7491

 79/231 [=========>....................] - ETA: 1s - loss: 0.5117 - accuracy: 0.7468

 87/231 [==========>...................] - ETA: 1s - loss: 0.5133 - accuracy: 0.7464

 95/231 [===========>..................] - ETA: 0s - loss: 0.5144 - accuracy: 0.7428

103/231 [============>.................] - ETA: 0s - loss: 0.5163 - accuracy: 0.7409

111/231 [=============>................] - ETA: 0s - loss: 0.5192 - accuracy: 0.7401

119/231 [==============>...............] - ETA: 0s - loss: 0.5202 - accuracy: 0.7366

127/231 [===============>..............] - ETA: 0s - loss: 0.5207 - accuracy: 0.7355

135/231 [================>.............] - ETA: 0s - loss: 0.5226 - accuracy: 0.7340

143/231 [=================>............] - ETA: 0s - loss: 0.5209 - accuracy: 0.7330

151/231 [==================>...........] - ETA: 0s - loss: 0.5214 - accuracy: 0.7295

159/231 [===================>..........] - ETA: 0s - loss: 0.5209 - accuracy: 0.7317

167/231 [====================>.........] - ETA: 0s - loss: 0.5192 - accuracy: 0.7328

175/231 [=====================>........] - ETA: 0s - loss: 0.5200 - accuracy: 0.7332

183/231 [======================>.......] - ETA: 0s - loss: 0.5209 - accuracy: 0.7302

191/231 [=======================>......] - ETA: 0s - loss: 0.5211 - accuracy: 0.7307

199/231 [========================>.....] - ETA: 0s - loss: 0.5215 - accuracy: 0.7299

207/231 [=========================>....] - ETA: 0s - loss: 0.5188 - accuracy: 0.7304

215/231 [==========================>...] - ETA: 0s - loss: 0.5177 - accuracy: 0.7318

223/231 [===========================>..] - ETA: 0s - loss: 0.5167 - accuracy: 0.7325

231/231 [==============================] - ETA: 0s - loss: 0.5186 - accuracy: 0.7315

231/231 [==============================] - 2s 8ms/step - loss: 0.5186 - accuracy: 0.7315 - val_loss: 0.5713 - val_accuracy: 0.6576


Epoch 4/10


  1/231 [..............................] - ETA: 13s - loss: 0.5382 - accuracy: 0.6562

  9/231 [>.............................] - ETA: 1s - loss: 0.5544 - accuracy: 0.6840 

 17/231 [=>............................] - ETA: 1s - loss: 0.5544 - accuracy: 0.7096

 25/231 [==>...........................] - ETA: 1s - loss: 0.5490 - accuracy: 0.7113

 33/231 [===>..........................] - ETA: 1s - loss: 0.5368 - accuracy: 0.7102

 41/231 [====>.........................] - ETA: 1s - loss: 0.5231 - accuracy: 0.7195

 49/231 [=====>........................] - ETA: 1s - loss: 0.5244 - accuracy: 0.7258

 56/231 [======>.......................] - ETA: 1s - loss: 0.5128 - accuracy: 0.7333

 64/231 [=======>......................] - ETA: 1s - loss: 0.5116 - accuracy: 0.7349

 72/231 [========>.....................] - ETA: 1s - loss: 0.5065 - accuracy: 0.7391

 80/231 [=========>....................] - ETA: 1s - loss: 0.5010 - accuracy: 0.7437

 88/231 [==========>...................] - ETA: 0s - loss: 0.5017 - accuracy: 0.7450

 96/231 [===========>..................] - ETA: 0s - loss: 0.5026 - accuracy: 0.7425

104/231 [============>.................] - ETA: 0s - loss: 0.5040 - accuracy: 0.7392

112/231 [=============>................] - ETA: 0s - loss: 0.5042 - accuracy: 0.7355

120/231 [==============>...............] - ETA: 0s - loss: 0.5013 - accuracy: 0.7378

128/231 [===============>..............] - ETA: 0s - loss: 0.5000 - accuracy: 0.7358

136/231 [================>.............] - ETA: 0s - loss: 0.4990 - accuracy: 0.7364

144/231 [=================>............] - ETA: 0s - loss: 0.5003 - accuracy: 0.7346

152/231 [==================>...........] - ETA: 0s - loss: 0.4999 - accuracy: 0.7344

160/231 [===================>..........] - ETA: 0s - loss: 0.5003 - accuracy: 0.7352

168/231 [====================>.........] - ETA: 0s - loss: 0.4997 - accuracy: 0.7368

176/231 [=====================>........] - ETA: 0s - loss: 0.4999 - accuracy: 0.7376

184/231 [======================>.......] - ETA: 0s - loss: 0.4982 - accuracy: 0.7373

192/231 [=======================>......] - ETA: 0s - loss: 0.5020 - accuracy: 0.7365

200/231 [========================>.....] - ETA: 0s - loss: 0.5015 - accuracy: 0.7366

208/231 [==========================>...] - ETA: 0s - loss: 0.5037 - accuracy: 0.7356

216/231 [===========================>..] - ETA: 0s - loss: 0.5034 - accuracy: 0.7352

223/231 [===========================>..] - ETA: 0s - loss: 0.5008 - accuracy: 0.7372

231/231 [==============================] - ETA: 0s - loss: 0.4999 - accuracy: 0.7382

231/231 [==============================] - 2s 8ms/step - loss: 0.4999 - accuracy: 0.7382 - val_loss: 0.5260 - val_accuracy: 0.7335


Epoch 5/10


  1/231 [..............................] - ETA: 15s - loss: 0.4643 - accuracy: 0.6562

  9/231 [>.............................] - ETA: 1s - loss: 0.5195 - accuracy: 0.6944 

 16/231 [=>............................] - ETA: 1s - loss: 0.4860 - accuracy: 0.7188

 23/231 [=>............................] - ETA: 1s - loss: 0.4642 - accuracy: 0.7459

 31/231 [===>..........................] - ETA: 1s - loss: 0.4742 - accuracy: 0.7500

 39/231 [====>.........................] - ETA: 1s - loss: 0.4767 - accuracy: 0.7484

 47/231 [=====>........................] - ETA: 1s - loss: 0.4762 - accuracy: 0.7500

 55/231 [======>.......................] - ETA: 1s - loss: 0.4786 - accuracy: 0.7489

 63/231 [=======>......................] - ETA: 1s - loss: 0.4803 - accuracy: 0.7465

 71/231 [========>.....................] - ETA: 1s - loss: 0.4802 - accuracy: 0.7491

 79/231 [=========>....................] - ETA: 1s - loss: 0.4759 - accuracy: 0.7516

 87/231 [==========>...................] - ETA: 0s - loss: 0.4802 - accuracy: 0.7518

 95/231 [===========>..................] - ETA: 0s - loss: 0.4837 - accuracy: 0.7510

103/231 [============>.................] - ETA: 0s - loss: 0.4827 - accuracy: 0.7491

111/231 [=============>................] - ETA: 0s - loss: 0.4829 - accuracy: 0.7486

119/231 [==============>...............] - ETA: 0s - loss: 0.4829 - accuracy: 0.7500

127/231 [===============>..............] - ETA: 0s - loss: 0.4820 - accuracy: 0.7515

135/231 [================>.............] - ETA: 0s - loss: 0.4810 - accuracy: 0.7514

143/231 [=================>............] - ETA: 0s - loss: 0.4851 - accuracy: 0.7496

151/231 [==================>...........] - ETA: 0s - loss: 0.4843 - accuracy: 0.7504

159/231 [===================>..........] - ETA: 0s - loss: 0.4842 - accuracy: 0.7508

167/231 [====================>.........] - ETA: 0s - loss: 0.4825 - accuracy: 0.7528

175/231 [=====================>........] - ETA: 0s - loss: 0.4851 - accuracy: 0.7513

183/231 [======================>.......] - ETA: 0s - loss: 0.4849 - accuracy: 0.7500

191/231 [=======================>......] - ETA: 0s - loss: 0.4848 - accuracy: 0.7502

199/231 [========================>.....] - ETA: 0s - loss: 0.4848 - accuracy: 0.7492

207/231 [=========================>....] - ETA: 0s - loss: 0.4849 - accuracy: 0.7492

215/231 [==========================>...] - ETA: 0s - loss: 0.4858 - accuracy: 0.7491

223/231 [===========================>..] - ETA: 0s - loss: 0.4868 - accuracy: 0.7468

231/231 [==============================] - ETA: 0s - loss: 0.4855 - accuracy: 0.7479

231/231 [==============================] - 2s 8ms/step - loss: 0.4855 - accuracy: 0.7479 - val_loss: 0.5404 - val_accuracy: 0.7140


Epoch 6/10


  1/231 [..............................] - ETA: 15s - loss: 0.6798 - accuracy: 0.6562

  9/231 [>.............................] - ETA: 1s - loss: 0.5475 - accuracy: 0.7049 

 17/231 [=>............................] - ETA: 1s - loss: 0.5250 - accuracy: 0.7188

 25/231 [==>...........................] - ETA: 1s - loss: 0.5144 - accuracy: 0.7200

 33/231 [===>..........................] - ETA: 1s - loss: 0.4938 - accuracy: 0.7330

 41/231 [====>.........................] - ETA: 1s - loss: 0.4911 - accuracy: 0.7416

 49/231 [=====>........................] - ETA: 1s - loss: 0.4853 - accuracy: 0.7455

 57/231 [======>.......................] - ETA: 1s - loss: 0.4807 - accuracy: 0.7429

 65/231 [=======>......................] - ETA: 1s - loss: 0.4815 - accuracy: 0.7437

 73/231 [========>.....................] - ETA: 1s - loss: 0.4857 - accuracy: 0.7449

 81/231 [=========>....................] - ETA: 1s - loss: 0.4821 - accuracy: 0.7496

 89/231 [==========>...................] - ETA: 0s - loss: 0.4791 - accuracy: 0.7511

 97/231 [===========>..................] - ETA: 0s - loss: 0.4759 - accuracy: 0.7535

105/231 [============>.................] - ETA: 0s - loss: 0.4803 - accuracy: 0.7524

113/231 [=============>................] - ETA: 0s - loss: 0.4781 - accuracy: 0.7517

121/231 [==============>...............] - ETA: 0s - loss: 0.4767 - accuracy: 0.7546

129/231 [===============>..............] - ETA: 0s - loss: 0.4777 - accuracy: 0.7529

137/231 [================>.............] - ETA: 0s - loss: 0.4797 - accuracy: 0.7523

145/231 [=================>............] - ETA: 0s - loss: 0.4822 - accuracy: 0.7513

153/231 [==================>...........] - ETA: 0s - loss: 0.4820 - accuracy: 0.7520

161/231 [===================>..........] - ETA: 0s - loss: 0.4831 - accuracy: 0.7516

169/231 [====================>.........] - ETA: 0s - loss: 0.4808 - accuracy: 0.7528

177/231 [=====================>........] - ETA: 0s - loss: 0.4793 - accuracy: 0.7544

185/231 [=======================>......] - ETA: 0s - loss: 0.4807 - accuracy: 0.7522

193/231 [========================>.....] - ETA: 0s - loss: 0.4805 - accuracy: 0.7523

201/231 [=========================>....] - ETA: 0s - loss: 0.4816 - accuracy: 0.7517

209/231 [==========================>...] - ETA: 0s - loss: 0.4839 - accuracy: 0.7509

217/231 [===========================>..] - ETA: 0s - loss: 0.4848 - accuracy: 0.7494

225/231 [============================>.] - ETA: 0s - loss: 0.4856 - accuracy: 0.7487

231/231 [==============================] - 2s 8ms/step - loss: 0.4854 - accuracy: 0.7479 - val_loss: 0.5226 - val_accuracy: 0.7259


Epoch 7/10


  1/231 [..............................] - ETA: 14s - loss: 0.7218 - accuracy: 0.7500

  9/231 [>.............................] - ETA: 1s - loss: 0.5381 - accuracy: 0.7188 

 17/231 [=>............................] - ETA: 1s - loss: 0.4897 - accuracy: 0.7371

 20/231 [=>............................] - ETA: 3s - loss: 0.4820 - accuracy: 0.7359

 27/231 [==>...........................] - ETA: 2s - loss: 0.4772 - accuracy: 0.7431

 35/231 [===>..........................] - ETA: 2s - loss: 0.4712 - accuracy: 0.7491

 43/231 [====>.........................] - ETA: 2s - loss: 0.4711 - accuracy: 0.7500

 51/231 [=====>........................] - ETA: 1s - loss: 0.4774 - accuracy: 0.7469

 59/231 [======>.......................] - ETA: 1s - loss: 0.4628 - accuracy: 0.7574

 67/231 [=======>......................] - ETA: 1s - loss: 0.4613 - accuracy: 0.7561

 75/231 [========>.....................] - ETA: 1s - loss: 0.4634 - accuracy: 0.7567

 83/231 [=========>....................] - ETA: 1s - loss: 0.4637 - accuracy: 0.7556

 90/231 [==========>...................] - ETA: 1s - loss: 0.4685 - accuracy: 0.7493

 98/231 [===========>..................] - ETA: 1s - loss: 0.4663 - accuracy: 0.7503

106/231 [============>.................] - ETA: 1s - loss: 0.4669 - accuracy: 0.7471

114/231 [=============>................] - ETA: 0s - loss: 0.4710 - accuracy: 0.7467

122/231 [==============>...............] - ETA: 0s - loss: 0.4709 - accuracy: 0.7459

130/231 [===============>..............] - ETA: 0s - loss: 0.4709 - accuracy: 0.7437

137/231 [================>.............] - ETA: 0s - loss: 0.4707 - accuracy: 0.7454

145/231 [=================>............] - ETA: 0s - loss: 0.4692 - accuracy: 0.7481

152/231 [==================>...........] - ETA: 0s - loss: 0.4655 - accuracy: 0.7508

159/231 [===================>..........] - ETA: 0s - loss: 0.4650 - accuracy: 0.7531

166/231 [====================>.........] - ETA: 0s - loss: 0.4703 - accuracy: 0.7500

174/231 [=====================>........] - ETA: 0s - loss: 0.4727 - accuracy: 0.7484

182/231 [======================>.......] - ETA: 0s - loss: 0.4728 - accuracy: 0.7469

190/231 [=======================>......] - ETA: 0s - loss: 0.4727 - accuracy: 0.7469

198/231 [========================>.....] - ETA: 0s - loss: 0.4717 - accuracy: 0.7484

206/231 [=========================>....] - ETA: 0s - loss: 0.4726 - accuracy: 0.7483

214/231 [==========================>...] - ETA: 0s - loss: 0.4726 - accuracy: 0.7494

222/231 [===========================>..] - ETA: 0s - loss: 0.4716 - accuracy: 0.7507

230/231 [============================>.] - ETA: 0s - loss: 0.4735 - accuracy: 0.7507

231/231 [==============================] - 2s 9ms/step - loss: 0.4734 - accuracy: 0.7505 - val_loss: 0.5223 - val_accuracy: 0.7291


Epoch 8/10


  1/231 [..............................] - ETA: 15s - loss: 0.5508 - accuracy: 0.7500

  8/231 [>.............................] - ETA: 1s - loss: 0.5064 - accuracy: 0.7227 

 16/231 [=>............................] - ETA: 1s - loss: 0.5030 - accuracy: 0.7324

 24/231 [==>...........................] - ETA: 1s - loss: 0.4968 - accuracy: 0.7357

 32/231 [===>..........................] - ETA: 1s - loss: 0.4833 - accuracy: 0.7520

 40/231 [====>.........................] - ETA: 1s - loss: 0.4839 - accuracy: 0.7516

 48/231 [=====>........................] - ETA: 1s - loss: 0.4736 - accuracy: 0.7591

 56/231 [======>.......................] - ETA: 1s - loss: 0.4760 - accuracy: 0.7528

 64/231 [=======>......................] - ETA: 1s - loss: 0.4793 - accuracy: 0.7490

 71/231 [========>.....................] - ETA: 1s - loss: 0.4789 - accuracy: 0.7465

 79/231 [=========>....................] - ETA: 1s - loss: 0.4803 - accuracy: 0.7460

 87/231 [==========>...................] - ETA: 0s - loss: 0.4752 - accuracy: 0.7489

 95/231 [===========>..................] - ETA: 0s - loss: 0.4767 - accuracy: 0.7490

103/231 [============>.................] - ETA: 0s - loss: 0.4781 - accuracy: 0.7476

111/231 [=============>................] - ETA: 0s - loss: 0.4796 - accuracy: 0.7497

119/231 [==============>...............] - ETA: 0s - loss: 0.4798 - accuracy: 0.7492

126/231 [===============>..............] - ETA: 0s - loss: 0.4771 - accuracy: 0.7527

134/231 [================>.............] - ETA: 0s - loss: 0.4754 - accuracy: 0.7551

142/231 [=================>............] - ETA: 0s - loss: 0.4752 - accuracy: 0.7540

150/231 [==================>...........] - ETA: 0s - loss: 0.4750 - accuracy: 0.7554

158/231 [===================>..........] - ETA: 0s - loss: 0.4735 - accuracy: 0.7547

166/231 [====================>.........] - ETA: 0s - loss: 0.4731 - accuracy: 0.7553

174/231 [=====================>........] - ETA: 0s - loss: 0.4734 - accuracy: 0.7540

182/231 [======================>.......] - ETA: 0s - loss: 0.4742 - accuracy: 0.7521

190/231 [=======================>......] - ETA: 0s - loss: 0.4736 - accuracy: 0.7512

198/231 [========================>.....] - ETA: 0s - loss: 0.4719 - accuracy: 0.7536

206/231 [=========================>....] - ETA: 0s - loss: 0.4728 - accuracy: 0.7544

214/231 [==========================>...] - ETA: 0s - loss: 0.4728 - accuracy: 0.7538

222/231 [===========================>..] - ETA: 0s - loss: 0.4713 - accuracy: 0.7549

230/231 [============================>.] - ETA: 0s - loss: 0.4702 - accuracy: 0.7556

231/231 [==============================] - 2s 8ms/step - loss: 0.4700 - accuracy: 0.7557 - val_loss: 0.5333 - val_accuracy: 0.7346


Epoch 9/10


  1/231 [..............................] - ETA: 15s - loss: 0.3922 - accuracy: 0.8125

  8/231 [>.............................] - ETA: 1s - loss: 0.4915 - accuracy: 0.7344 

 16/231 [=>............................] - ETA: 1s - loss: 0.4772 - accuracy: 0.7500

 24/231 [==>...........................] - ETA: 1s - loss: 0.4775 - accuracy: 0.7487

 32/231 [===>..........................] - ETA: 1s - loss: 0.4588 - accuracy: 0.7549

 40/231 [====>.........................] - ETA: 1s - loss: 0.4501 - accuracy: 0.7680

 47/231 [=====>........................] - ETA: 1s - loss: 0.4604 - accuracy: 0.7613

 55/231 [======>.......................] - ETA: 1s - loss: 0.4611 - accuracy: 0.7557

 62/231 [=======>......................] - ETA: 1s - loss: 0.4629 - accuracy: 0.7530

 70/231 [========>.....................] - ETA: 1s - loss: 0.4688 - accuracy: 0.7478

 78/231 [=========>....................] - ETA: 1s - loss: 0.4745 - accuracy: 0.7448

 86/231 [==========>...................] - ETA: 1s - loss: 0.4704 - accuracy: 0.7471

 94/231 [===========>..................] - ETA: 0s - loss: 0.4691 - accuracy: 0.7480

102/231 [============>.................] - ETA: 0s - loss: 0.4659 - accuracy: 0.7500

110/231 [=============>................] - ETA: 0s - loss: 0.4685 - accuracy: 0.7497

118/231 [==============>...............] - ETA: 0s - loss: 0.4667 - accuracy: 0.7516

125/231 [===============>..............] - ETA: 0s - loss: 0.4682 - accuracy: 0.7517

133/231 [================>.............] - ETA: 0s - loss: 0.4682 - accuracy: 0.7514

141/231 [=================>............] - ETA: 0s - loss: 0.4672 - accuracy: 0.7524

149/231 [==================>...........] - ETA: 0s - loss: 0.4685 - accuracy: 0.7525

157/231 [===================>..........] - ETA: 0s - loss: 0.4698 - accuracy: 0.7516

165/231 [====================>.........] - ETA: 0s - loss: 0.4674 - accuracy: 0.7542

173/231 [=====================>........] - ETA: 0s - loss: 0.4687 - accuracy: 0.7522

181/231 [======================>.......] - ETA: 0s - loss: 0.4671 - accuracy: 0.7543

189/231 [=======================>......] - ETA: 0s - loss: 0.4656 - accuracy: 0.7560

197/231 [========================>.....] - ETA: 0s - loss: 0.4638 - accuracy: 0.7576

205/231 [=========================>....] - ETA: 0s - loss: 0.4656 - accuracy: 0.7569

212/231 [==========================>...] - ETA: 0s - loss: 0.4643 - accuracy: 0.7572

220/231 [===========================>..] - ETA: 0s - loss: 0.4654 - accuracy: 0.7560

228/231 [============================>.] - ETA: 0s - loss: 0.4672 - accuracy: 0.7540

231/231 [==============================] - 2s 8ms/step - loss: 0.4669 - accuracy: 0.7544 - val_loss: 0.5315 - val_accuracy: 0.7270


Epoch 10/10


  1/231 [..............................] - ETA: 15s - loss: 0.4419 - accuracy: 0.8125

  9/231 [>.............................] - ETA: 1s - loss: 0.4466 - accuracy: 0.7674 

 17/231 [=>............................] - ETA: 1s - loss: 0.4642 - accuracy: 0.7629

 25/231 [==>...........................] - ETA: 1s - loss: 0.4688 - accuracy: 0.7487

 33/231 [===>..........................] - ETA: 1s - loss: 0.4614 - accuracy: 0.7538

 41/231 [====>.........................] - ETA: 1s - loss: 0.4598 - accuracy: 0.7599

 49/231 [=====>........................] - ETA: 1s - loss: 0.4545 - accuracy: 0.7589

 57/231 [======>.......................] - ETA: 1s - loss: 0.4603 - accuracy: 0.7577

 65/231 [=======>......................] - ETA: 1s - loss: 0.4664 - accuracy: 0.7543

 73/231 [========>.....................] - ETA: 1s - loss: 0.4642 - accuracy: 0.7526

 81/231 [=========>....................] - ETA: 1s - loss: 0.4645 - accuracy: 0.7504

 89/231 [==========>...................] - ETA: 0s - loss: 0.4670 - accuracy: 0.7461

 97/231 [===========>..................] - ETA: 0s - loss: 0.4663 - accuracy: 0.7484

104/231 [============>.................] - ETA: 0s - loss: 0.4671 - accuracy: 0.7479

112/231 [=============>................] - ETA: 0s - loss: 0.4678 - accuracy: 0.7480

120/231 [==============>...............] - ETA: 0s - loss: 0.4655 - accuracy: 0.7510

128/231 [===============>..............] - ETA: 0s - loss: 0.4650 - accuracy: 0.7517

136/231 [================>.............] - ETA: 0s - loss: 0.4631 - accuracy: 0.7530

144/231 [=================>............] - ETA: 0s - loss: 0.4636 - accuracy: 0.7513

152/231 [==================>...........] - ETA: 0s - loss: 0.4649 - accuracy: 0.7514

160/231 [===================>..........] - ETA: 0s - loss: 0.4611 - accuracy: 0.7521

168/231 [====================>.........] - ETA: 0s - loss: 0.4605 - accuracy: 0.7543

176/231 [=====================>........] - ETA: 0s - loss: 0.4583 - accuracy: 0.7557

184/231 [======================>.......] - ETA: 0s - loss: 0.4577 - accuracy: 0.7563

192/231 [=======================>......] - ETA: 0s - loss: 0.4589 - accuracy: 0.7550

200/231 [========================>.....] - ETA: 0s - loss: 0.4585 - accuracy: 0.7553

207/231 [=========================>....] - ETA: 0s - loss: 0.4571 - accuracy: 0.7569

214/231 [==========================>...] - ETA: 0s - loss: 0.4570 - accuracy: 0.7567

222/231 [===========================>..] - ETA: 0s - loss: 0.4569 - accuracy: 0.7566

230/231 [============================>.] - ETA: 0s - loss: 0.4586 - accuracy: 0.7550

231/231 [==============================] - 2s 8ms/step - loss: 0.4587 - accuracy: 0.7546 - val_loss: 0.5411 - val_accuracy: 0.6918


In [27]:
loss, accuracy = model.evaluate(test_ds)
print("Accuracy", accuracy)

 1/73 [..............................] - ETA: 1s - loss: 0.3233 - accuracy: 0.8125

10/73 [===>..........................] - ETA: 0s - loss: 0.5503 - accuracy: 0.6656

19/73 [======>.......................] - ETA: 0s - loss: 0.5485 - accuracy: 0.6628

28/73 [==========>...................] - ETA: 0s - loss: 0.5188 - accuracy: 0.6875

38/73 [==============>...............] - ETA: 0s - loss: 0.5265 - accuracy: 0.6850

47/73 [==================>...........] - ETA: 0s - loss: 0.5275 - accuracy: 0.6855

57/73 [======================>.......] - ETA: 0s - loss: 0.5205 - accuracy: 0.6870

67/73 [==========================>...] - ETA: 0s - loss: 0.5168 - accuracy: 0.6908

73/73 [==============================] - 0s 6ms/step - loss: 0.5155 - accuracy: 0.6941


Accuracy 0.6941074728965759


핵심 포인트: 일반적으로 크고 복잡한 데이터셋일 경우 딥러닝 모델에서 최선의 결과를 얻습니다. 이런 작은 데이터셋에서는 기본 모델로 결정 트리(decision tree)나 랜덤 포레스트(random forest)를 사용하는 것이 권장됩니다. 이 튜토리얼의 목적은 정확한 모델을 훈련하는 것이 아니라 정형 데이터를 다루는 방식을 설명하는 것입니다. 실전 데이터셋을 다룰 때 이 코드를 시작점으로 사용하세요.

## 그 다음엔

정형 데이터를 사용한 분류 작업에 대해 배우는 가장 좋은 방법은 직접 실습하는 것입니다. 실험해 볼 다른 데이터셋을 찾아서 위와 비슷한 코드를 사용해 모델을 훈련해 보세요. 정확도를 향상시키려면 모델에 포함할 특성과 표현 방법을 신중하게 생각하세요.